Remove Makefile and it's references
keycloak/keycloak-nodejs-connect pull request #324
Opened 2022-01-19 13:08 UTC by helio-frota

2022-01-19 16:15 UTC, jonkoops requested changes

2022-01-19 16:16 UTC, jonkoops commented
I agree that a Makefile adds very little and just increases complexity since we already have NPM to run tasks. @edewit WDYT?

2022-01-19 16:20 UTC, edewit approved these changes

2022-01-19 18:25 UTC, helio-frota commented on package.json
> +    "pretest": "npm run lint",
@jonkoops @edewit thanks for the review. PR updated with linting task removed. 
That really is an optional workflow development thing

2022-01-20 10:23 UTC, jonkoops approved these changes

2022-01-20 10:24 UTC, jonkoops commented
This looks great, thanks of helping us clean this up @helio-frota!

2022-01-20 10:25 UTC, edewit approved these changes

2022-01-20 10:25 UTC, merged